import { formatAmount, formatDateTime, DESCRIPTION_MAX_LENGTH, SYLLABUS_MAX_LENGTH } from './courseUtils';

/**
 * Declarative registry for the Course feature.
 *
 * Everything screen-specific lives here as data so the components stay
 * generic: adding a backend field means adding one entry to FORM_SECTIONS
 * and one to VIEW_FIELDS, with no changes to CourseManagement or the modals.
 */

export const MANAGE_ROLES = ['ADMIN', 'SUPER_ADMIN'];

export const FORM_SECTIONS = [
  {
    id: 'basics',
    title: 'Basic information',
    description: 'Identity used across catalogues, receipts and reports.',
    fields: [
      {
        name: 'name',
        label: 'Course name',
        type: 'text',
        required: true,
        maxLength: 100,
        span: 2,
        placeholder: 'e.g. Advanced Java Programming',
      },
      {
        name: 'code',
        label: 'Course code',
        type: 'text',
        required: true,
        maxLength: 20,
        span: 2,
        autoGenerated: true,
        placeholder: 'Generated from the course name',
        help: 'Unique public identifier. A-Z, 0-9 and hyphen, 2-20 characters.',
      },
    ],
  },
  {
    id: 'pricing',
    title: 'Pricing & capacity',
    description: 'Commercial terms used during admissions and fee calculation.',
    fields: [
      { name: 'durationMonths', label: 'Duration (months)', type: 'number', required: true, min: 1, span: 1 },
      { name: 'maxStudents', label: 'Max students', type: 'number', required: true, min: 1, span: 1 },
      { name: 'fee', label: 'Fee', type: 'number', required: true, min: 0, step: '0.01', span: 1 },
      {
        name: 'discountFee',
        label: 'Discounted fee',
        type: 'number',
        min: 0,
        step: '0.01',
        span: 1,
        help: 'Optional. Leave blank when no concession applies.',
      },
    ],
  },
  {
    id: 'content',
    title: 'Content',
    description: 'Copy shown on the public course page.',
    fields: [
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        rows: 4,
        span: 2,
        maxLength: DESCRIPTION_MAX_LENGTH,
      },
      {
        name: 'syllabus',
        label: 'Syllabus',
        type: 'textarea',
        rows: 6,
        span: 2,
        maxLength: SYLLABUS_MAX_LENGTH,
        help: 'Module-by-module outline.',
      },
    ],
  },
  {
    id: 'media',
    title: 'Media',
    description: 'Optional cover art for cards and the catalogue hero.',
    fields: [
      {
        name: 'imageUrl',
        label: 'Image URL',
        type: 'url',
        span: 2,
        maxLength: 500,
        placeholder: 'https://…',
      },
    ],
  },
];

export const VIEW_SECTIONS = [
  {
    id: 'overview',
    title: 'Overview',
    fields: [
      { key: 'name', label: 'Course name' },
      { key: 'code', label: 'Course code', mono: true },
      { key: 'durationMonths', label: 'Duration (months)' },
      { key: 'maxStudents', label: 'Max students' },
    ],
  },
  {
    id: 'commercial',
    title: 'Pricing',
    fields: [
      { key: 'fee', label: 'Fee', render: (v) => formatAmount(v) },
      { key: 'discountFee', label: 'Discounted fee', render: (v) => (v == null ? '—' : formatAmount(v)) },
    ],
  },
  {
    id: 'content',
    title: 'Content',
    fields: [
      { key: 'description', label: 'Description', empty: 'No description provided.' },
      { key: 'syllabus', label: 'Syllabus', empty: 'No syllabus provided.' },
    ],
  },
  {
    id: 'audit',
    title: 'Record',
    fields: [
      { key: 'createdAt', label: 'Created', render: (v) => formatDateTime(v) },
      { key: 'updatedAt', label: 'Last updated', render: (v) => formatDateTime(v) },
    ],
  },
];

export const CODE_CHECK = {
  idle: { tone: 'muted', message: '' },
  checking: { tone: 'muted', message: 'Checking availability...' },
  available: { tone: 'success', message: 'Code is available.' },
  taken: { tone: 'danger', message: 'That code is already in use.' },
  error: { tone: 'danger', message: 'Could not verify the code. You can still try to save.' },
};

/**
 * Builds the DataTable column contract. Kept as a factory because the actions
 * column needs the row callbacks, which only the container can supply.
 */
export function buildTableColumns({ canManage, busyId, onView, onEdit, onPublish, onToggleActive, onDelete }) {
  return [
    { key: 'code', label: 'Code', className: 'w-28 font-mono text-xs text-slate-500' },
    {
      key: 'name',
      label: 'Course',
      render: (row) => (
        <div className="min-w-0">
          <div className="truncate font-medium text-navy-dark">{row.name}</div>
          <div className="text-xs text-slate-500">ID {row.id}</div>
        </div>
      ),
    },
    { key: 'durationMonths', label: 'Duration', className: 'w-28', render: (row) => `${row.durationMonths} mo` },
    { key: 'fee', label: 'Fee', className: 'w-28', render: (row) => formatAmount(row.fee) },
    {
      key: 'active',
      label: 'Status',
      className: 'w-24',
      render: (row) => (
        <span
          className={`badge ${row.active ? 'bg-status-easy-bg text-status-easy-text' : 'bg-slate-100 text-slate-600'}`}
        >
          {row.active ? 'Active' : 'Inactive'}
        </span>
      ),
    },
    {
      key: 'published',
      label: 'Published',
      className: 'w-28',
      render: (row) => (
        <span
          className={`badge ${
            row.published ? 'bg-info-banner-bg text-info-banner-text' : 'bg-slate-100 text-slate-600'
          }`}
        >
          {row.published ? 'Published' : 'Draft'}
        </span>
      ),
    },
    {
      key: 'actions',
      label: 'Actions',
      className: 'w-56 text-right',
      render: (row) => {
        const isBusy = busyId === row.id;
        if (!canManage) {
          return (
            <button type="button" className="btn btn-ghost" onClick={() => onView(row)}>
              View
            </button>
          );
        }
        return (
          <div className="flex flex-wrap justify-end gap-1">
            <button type="button" className="btn btn-ghost" onClick={() => onView(row)} disabled={isBusy}>
              View
            </button>
            <button type="button" className="btn btn-ghost" onClick={() => onEdit(row)} disabled={isBusy}>
              Edit
            </button>
            {!row.published && (
              <button type="button" className="btn btn-outline" onClick={() => onPublish(row)} disabled={isBusy}>
                Publish
              </button>
            )}
            <button
              type="button"
              className="btn btn-ghost"
              onClick={() => onToggleActive(row)}
              disabled={isBusy}
            >
              {row.active ? 'Deactivate' : 'Activate'}
            </button>
            <button type="button" className="btn btn-danger" onClick={() => onDelete(row)} disabled={isBusy}>
              Delete
            </button>
          </div>
        );
      },
    },
  ];
}
