apiVersion: apps/v1
kind: Deployment
metadata:
  name: studypoint-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studypoint-mysql
  template:
    metadata:
      labels:
        app: studypoint-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: studypoint-secrets
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: studypoint-config
                  key: DB_NAME
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mysql-data
          emptyDir: {}